version: "3"
services:

  postgres:
    image: postgres:latest
    environment:
       POSTGRES_USER: ${POSTGRES_USER:-admin}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
       POSTGRES_DB: ${POSTGRES_DB:-nestjs}
       PG_DATA: /var/lib/postgresql/data
       POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - $HOME/goinfre/pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  server:
    build: ./srcs/server
    expose:
      - ${PORT}
    environment:
       POSTGRES_PORT: ${POSTGRES_PORT:-5432}
       POSTGRES_USER: ${POSTGRES_USER:-admin}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
       POSTGRES_DB: ${POSTGRES_DB:-nestjs}
       POSTGRES_HOST: postgres
       HOST: ${API_HOST:-localhost}
       PORT: ${PORT:-3000}
       JWT_SECRET: ${JWT_SECRET}
       JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
       REACT_APP_PORT: ${REACT_APP_PORT:-4000}
       REACT_APP_BASE_URL: ${REACT_APP_BASE_URL:-localhost}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./srcs/server/src:/srv/app/overkillpong-server/src
    command: npm run start:dev
    depends_on:
      - postgres

  client:
    build: ./srcs/client
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT:-4000}
      REACT_APP_API_HOST: ${API_HOST:-server}
      REACT_APP_API_PORT: ${PORT-3000}
      PROXY: http://${API_HOST:-localhost}:${PORT:-3000}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./srcs/client/src:/srv/app/overkillpong-client/src
      - ./srcs/client/public:/srv/app/overkillpong-client/public
    links:
      - server
    command: npm run start
