version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - $HOME/goinfre/postgres:$HOME/goinfre/postgres
      - $HOME/gitlab/backend/script:$HOME/script
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - $HOME/goinfre/pgadmin:$HOME/goinfre/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
    command: sh -c "$HOME/script/initdb.sh"

networks:
  postgres:
    driver: bridge
