version: "3"
services:
  server:
    build: ./srcs/server
    expose:
      - ${POSTGRES_PORT}
    environment:
       POSTGRES_HOST: ${POSTGRES_HOST:-http://localhost:3000}
       POSTGRES_PORT: ${POSTGRES_PORT:-5432}
       POSTGRES_USER: ${POSTGRES_USER:-admin}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
       POSTGRES_DB: ${POSTGRES_DB:-nestjs}
       JWT_SECRET: ${JWT_SECRET}
       JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - $HOME/goinfre/overkillpong/server/src:/srv/app/overkillpong-server/src
    command: npm run start:dev

  client:
    build: ./srcs/client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - $HOME/goinfre/overkillpong/client/src:/srv/app/overkillpong-client/src
    links:
      - server
    command: npm run start
